---
output: pdf_document
latex_engine: xelatex
---

Dr. Anthony Caravaggi
=============================
University of South Wales, Upper Glyntaff Campus, 9 Graig Fach, Pontypridd CF37 4BB     
**E-mail** [ar.caravaggi@gmail.com](ar.caravaggi@gmail.com) | **Website** [http://arcaravaggi.github.io](http://arcaravaggi.github.io)  | **Twitter** @[thonoir](https://twitter.com/thonoir)  
**GitHub** [arcaravaggi.github.io](https://arcaravaggi.github.io) | [Google Scholar](https://scholar.google.co.uk/citations?user=PXf81KIAAAAJ&hl=en)   

### Career History
**2019-** Lecturer in Natural History, [University of South Wales](http://www.southwales.ac.uk)   
**2017-19** Postdoctoral researcher; [Supporting Hen harriers in Novel Environments (SHINE)](https://www.ucc.ie/en/forestecology/research/shine/)  
School of Biological, Earth and Environmental Sciences, [University College Cork](http://www.ucc.ie/en/)    
**2017-18** Visiting Research Fellow; movement ecology, invasive species       
School of Biological Sciences, [Queen's University Belfast](http://www.qub.ac.uk/schools/SchoolofBiologicalSciences/) 

### Education
**2016** PhD conservation biology/invasion ecology, [Queen's University Belfast](http://www.qub.ac.uk/schools/SchoolofBiologicalSciences/)   
**2011**	MRes Biodiversity and Conservation, [University of Leeds](https://www.leeds.ac.uk/)  
**2009**	BSc Zoology with Conservation (Hons), [Bangor University](https://www.bangor.ac.uk/) 

### Professional activities   
<!---
BEES outreach cmmttee
--->

**Associate Editor**: Remote Sensing in Ecology and Conservation  

**Peer reviewer**:	African Journal of Ecology; Austral Ecology; Biological Conservation; Bird Study; Canadian Journal of Zoology; Diversity and Distributions; Global Change Biology; Journal of Natural History; Journal of Zoology; Mammal Communications; Mammal Research; Mammal Review; PeerJ; PLOS One; Remote Sensing in Ecology and Conservation; The European Zoological Journal; Zoo Biology.    

<!---
2019 **Peer reviewer**: Journal of Zoology; JZO-12-18-OM-355   
2018 **Peer reviewer**; PeerJ; 31160v1   
2018 **Peer reviewer**; Remote Sensing in Ecology and Conservation; RSEC-2018-02-0010   
2018 **Handling Editor**; Remote Sensing in Ecology and Conservation; RSEC-2018-05-0023   
2018 **Peer reviewer**; Austral Ecology; AEC-18-088-OA   
2018 **Peer reviewer**; Remote Sensing in Ecology and Conservation; RSEC-2018-02-0010   
2018 **Peer reviewer**; African Journal of Ecology; AFJE-18-160   
2018 **Peer reviewer**, The European Zoological Journal; TIZO-2018-0027    
2018 **Peer reviewer**, Bird Study; BS-2017-150  
2018 **Peer reviewer**, Mammal Communications; MC1801
2018 **Peer reviewer**, Mammal Research; ACTH-D-18-00004  
2017 **Peer reviewer**, Biological Conservation; BIOC_2017_1604
2017 **Peer reviewer**, Journal of Zoology; JZO-11-17-OM-319  
2017 **Peer reviewer**, PLOS One; PONE-D-17-21900_R1  
2017 **Peer reviewer**, Journal of Zoology; JZO-06-17-OM-179.R1  
2017 **Peer reviewer**, Mammal Review; MAMMAL-17-59 (double-blind)  
2017 **Peer reviewer**, Global Change Biology; GCB-17-1296  
2017 **Peer reviewer**, PLOS One; PONE-D-17-21900  
2017 **Peer reviewer**, Journal of Zoology; JZO-04-17-OM-122.R1      
2017 **Peer reviewer**, Invasive Species Compendium, *Lepus europaeus*, http://www.cabi.org/isc/datasheet/77227   
2017 **Peer reviewer**, Journal of Zoology; JZO-06-17-OM-179    
2017 **Peer Reviewer**, Journal of Natural History; TNAH-OA 17-150    
2017 **Peer reviewer**, Canadian Journal of Zoology; cjz-2017-0049   
2017 **Peer reviewer**, Journal of Zoology; JZO-04-17-OM-122   
2016 **Peer reviewer**, Remote Sensing in Ecology and Conservation; RSEC-2016-03-0010   
2015 **Peer reviewer**, Zoo Biology   
2013 **Peer reviewer**, Mammal Research 

Funding
2018 EPP IP-2018-01-1693; Croatian Science Foundation    
--->

**Funding review**: British Ecological Society Grant Review College; Croatian Science Foundation.  

**Consultant**:	The Hen Harrier Reintroduction Project (University of Exeter and Natural England).  

## Research   
I employ field and laboratory-based experiments, along with archival data, to answer specific questions relating to the ecology of species and communities to inform conservation, management and policy-related processes. My current work includes an analysis of mammal activity patterns, landscape-scale habitat and distribution modelling, quantification of the impacts of non-native rodents on insular seabirds and an assessment of wildlife management practises.   

**Research interests**; Conservation biology; urban ecology; invasive species; population & community ecology; movement & spatial ecology; rare and endangered species; sustainability; rewilding; citizen science; remote sensing.   

## Peer-Reviewed Publications  

<!---
??? Biotweeps
??? Systematic review of invasive species assessment protocols
??? NI data compared to Scotland (Roo Campbell)  
??? Habitat association & occupancy from NI data  
??? Twitter conferences
??? Wildlife bycatch from camera traps
??? Camera trap database

Behaviour and temperature review
Passerine tarsi
Review of bird disturbance distances
Meta-analysis of attitudes to wildlife control

Hen harrier papers:
- GPS tracking w. dario & mark wilson
- biometrics; Ireland vs UK (???)
- Review of ecology in Ireland
- forest management and habitat value for HH  (???)
- Alternatives to Red Zones
- Predation surveys
- Small mammals???

Hare movement analysis with Marco

Hare survey of Ireland

*In development (working titles; focal journal given where appropriate)*

Threats to HH

**Caravaggi A**, McCarthy A, Irwin S, O'Halloran J. A review of the conservation ecology of Hen Harriers, Circus cyaneus, in Ireland. *Biology and the Environment*.  

**Caravaggi A**, Middleton O, Robertson D, Broom C, Lockwood H, Irwin S, Smith C, Jones Z, Thompson R, Watts S, Cooper P. What's on your campus? Non-human mammals at UK Universities revealed via citizen science. *Wildlife Research*.  

**Caravaggi A**, Turner D, Cameron T. I've got a bad feeling about this: a study into factors affecting reed-nesting birds. *F1000Research*.  

English H, **Caravaggi A**. The historical and present distribution of wallabies in the UK. Mammal Review.   

**Caravaggi A**, Rabaiotti D, Evans A, Evans T, O'Neill H, Gold S. A meta-analysis of public opinion on the lethal control of wildlife.   

Rabaiotti D, Raby C, **Caravaggi A**, O'Neill H. How does temperature influence the behaviour of terrestrial vertebrates?    

**Caravaggi A**, Fernandez-Bellon D, Wilson M, Irwin S, O'Halloran J. Foraging behaviour and habitat use of Hen Harriers in Ireland from GPS tracking. *Journal of Raptor Research*.   

**Caravaggi A**, Irwin S, O'Halloran J. Alternatives to Red Zones for Hen Harrier conservation in Ireland.   

**Caravaggi A**, Facey R, Smith J, De La Hera Fernandez I, Shewring M, Bayley S. The relationship between minimum and maximum tarsus measurements of passerine birds. *Bird Study*.   

Fennelly R, **Caravaggi A**. A review of Flight Initiation Distances for birds of conservation concern in Ireland. *Biology and the Environment*.   

--->
2019   
Hayward MW, Scanlon RJ, Callen A, *et al*. including **Caravaggi A**. (*in review*) Reintroducing rewilding to restoration - a search for novelty. *Journal of Applied Conservation*.   

2018
**Caravaggi A**, Vallely M-C, Hogg K, Freeman M, Fadaei E, Reid N, Tosh D. Seasonal and predator-prey effects on circadian activity of free-ranging mammals revealed by camera traps. *PeerJ*. 6:e5827. doi: [10.7717/peerj.5827](https://doi.org/10.7717/peerj.5827)           

**Caravaggi A**, Cuthbert RJ, Ryan RG, Cooper J, Bond AL. The cumulative impacts of introduced house mice on the breeding success of nesting seabirds on Gough Island. *Ibis*. doi: [10.1111/ibi.12664](https://onlinelibrary.wiley.com/doi/10.1111/ibi.12664)   

**Caravaggi A**, Plowman A, Wright D, Bishop C. The composition of captive ruffed lemur (*Varecia* spp.) diets in UK zoological collections, with reference to the problems of obesity and iron storage disease.  *Journal of Zoo Animal Research*. 6: 41-49. doi: [10.19227/jzar.v6i2.301](https://doi.org/10.19227/jzar.v6i2.301)    


Havlin P, **Caravaggi A**, Montgomery WI. The diet and abundance of an introduced insular population of Red-Necked Wallabies, *Macropus rufogriseus*. *Canadian Journal of Zoology*. 96: 357-365. doi: [10.1139/cjz-2017-0090](10.1139/cjz-2017-0090) 

2017  
O'Halloran J, Kelly TC, Quinn JL, Irwin S, Fernandez-Bellon D, **Caravaggi A**, Smddy P. Current ornithological research in Ireland: seventh Ornithological Research Conference, UCC, November 2017. *Irish Birds*. 10: 598-638.   

**Caravaggi A**, Montgomery WI, Reid N. Management and control of invasive brown hares (*Lepus europaeus*): contrasting attitudes of selected environmental stakeholders and the wider rural community. *Proceedings of the Royal Irish Academy: Biology & Environment*. 117B: 1-11. doi: [10.3318/bioe.2017.08](http://www.jstor.org/stable/10.3318/bioe.2017.08)     

Tennant JP, Graziotin D, Jacques DC, *et al*. including **Caravaggi A**. A multi-disciplinary perspective on emergent and future innovations in peer review. *F1000Research*. 6:1151. doi: [10.12688/f1000research.12037.3](https://f1000research.com/articles/6-1151/v3)  

**Caravaggi A**, Banks P, Burton C, Finlay CMV, Hayward M, Haswell, PM, Rowcliffe JM, Wood M. A review of camera trapping for conservation behaviour research. *Remote Sensing in Ecology and Conservation*. doi: [10.1002/rse2.48](http://onlinelibrary.wiley.com/doi/10.1002/rse2.48/abstract)   

**Caravaggi A**.  remBoot: An R package for Random Encounter Modelling. *Journal of Open Source Software*. 2(10). doi: [10.21105/joss.00176](http://joss.theoj.org/papers/10.21105/joss.00176)

**Caravaggi A**, Leach K, Santilli F, Rintala J, Helle P, Tiainen J, Bisi F, Martinoli A, Montgomery WI, Reid N. Niche overlap of mountain hare subspecies and the vulnerability of their ranges to invasion by the European hare; the (bad) luck of the Irish. *Biological Invasions*. 19(2): 655-674. doi: [10.1007/s10530-016-1330-z ](http://link.springer.com/article/10.1007/s10530-016-1330-z)

2016   
**Caravaggi A**, Zaccaroni M, Riga F, Schai-Braun SC, Dick JTA, Montgomery WI, Reid N (2016) An invasive-native mammalian species replacement process captured by camera trap survey Random Encounter Models. *Remote Sensing in Ecology and Conservation*. 2: 45-58. doi: [10.1002/rse2.11](http://onlinelibrary.wiley.com/doi/10.1002/rse2.11/abstract)

2015   
**Caravaggi A**, Montgomery WI, Reid N et al. (2015) Range expansion and comparative habitat use of insular, congeneric lagomorphs: invasive European hares *Lepus europaeus* and endemic Irish hares *Lepus timidus hibernicus*. *Biological Invasions*. 17(2): 687-698. doi: [10.1007/s10530-014-0759-1](http://link.springer.com/article/10.1007/s10530-014-0759-1)

> *In review*   

**Caravaggi A**, Irwin S, Lusby J, Ruddock M, O'Toole L, Mee A, Nagle T, O'Neill S, Tierney D, O'Halloran J. Factors affecting territory site selection and breeding parameters of Hen Harriers, *Circus cyaneus*, in Ireland. *Ibis*.  

**Caravaggi A**, Irwin S, Lusby J, Ruddock M, O'Toole L, Mee A, Nagle T, O'Neill S, Tierney D, O'Halloran J. Anthropogenic pressures on Hen Harrier breeding habitat. *Bird Conservation International*.    


> *Book chapters*

2018   
**Caravaggi A**. Lagomorpha Life History. In: *Encyclopedia of Animal Cognition and Behavior*, Vonk J, Shackelford TK (eds.) doi: [10.1007/978-3-319-47829-6_1206-1](https://link.springer.com/referenceworkentry/10.1007/978-3-319-47829-6_1206-1)     

**Caravaggi A**. Lagomorpha Navigation. In: *Encyclopedia of Animal Cognition and Behavior*, Vonk J, Shackelford TK (eds.) doi: [https://doi.org/10.1007/978-3-319-47829-6_1164-1](https://link.springer.com/referenceworkentry/10.1007/978-3-319-47829-6_1164-1)    


> *Technical reports*

2018   
McGowan N, Dingerkus K, Stone R, **Caravaggi A**, et al. Hare Survey of Ireland 2018/2019: Interim Report (June) 2018. Report produced for the Department of Arts, Heritage and the Gaeltacht.   

> *Other publications*

2017
**Caravaggi A**, James K. Twittersphere: Conferencing in 140 characters. *Nature* [Correspondence] 549: 458. doi: [doi:10.1038/549458d](http://www.nature.com/nature/journal/v549/n7673/full/549458d.html)    

## Teaching
As a teacher I aim to provide my students with skills, knowledge and confidence critical to their academic and personal development. I take an inclusive approach, developing strong relationships and encouraging discussion.

> *Qualifications*

2018  	
Postgraduate Certificate in Teaching and Learning in Higher Education, University of London (*ongoing*).   


> **Module development**

2017  
*BL6024 Quantitative skills for biologists using R*    
Quantitative skills required by postgraduate students to successfully conduct and publish their research, with a focus on data analysis and graphing, statistics, and basic modelling, as generally implemented by zoologists and ecologists. Supported by a new R Peer Group mailing list and pop-up clinics.  

> **Teaching**   

2019	Biodiversity & biogeography   
      MSc research projects   
	    Research methods in natural history   
	    Terrestrial & aquatic conservation   
2018  BL6024 Quantitative skills for biologists using R.
      Conservation biology.
2017	BL6024 Quantitative skills for biologists using R.   
2015	Introduction to GIS (*Teaching Assistant*).  
    	Animal Biology (*Teaching Assistant*).   
      Undergraduate residential field course.      	
2014  Undergraduate residential field course.   

> *Field-based teaching*

2016	South American rainforest biodiversity and conservation (Ecuador).     
2015	Undergraduate residential field course, Northern Ireland.   
2014	Undergraduate residential field course, Northern Ireland.   
    	Bird survey techniques.   


> **Project supervision**  

2018  
PhD. Samantha Ball, *Managing hares at Dublin airport*. University College Cork.    
Erasmus+.	Enrique Da Paz, *Hen Harrier distribution under a changing climate*,	University College Cork/University of Barcelona.   
  
2017-19    
MRes. Alan McCarthy, *Top-down and bottom-up processes and Hen Harriers in Ireland*. University College Cork   
2017   
BSc.	Chloe O'Mahoney, *Regional variation in Hen Harrier chick growth rates*. University College Cork.   
  

2015  
MSc.	Ashley Irwin,	*Surveying otters along an urban-rural gradient using camera traps*. Queen's University Belfast.   
MSc.  Lauren Finley, *Estimaing hare population densities using camera traps*. Queen's University Belfast.   
BSc.	Paige Havlin, *Population size, habitat associations and diet of wallabies on the Isle of Man*.	Queen's University Belfast.   
Scientists Without Borders.	Lazaro Silva, *Camera trapping for hares*.	Queen's University Belfast.   
  
2014	  
BSc.	Mengyi Liu, *Behaviour and stress in sympatric hare species*.	Queen's University Belfast.    
BSc.	Claire Molloy, *Ethology of hares in Ireland*	Queen's University Belfast.   
   
2013	  
BSc.	Ashley Irwin, *The nutritional composition of vegetation associated with hares*.	Queen's University Belfast.   

> **Instruction and demonstration**   

2016-17 Course tutor: ornithology, camera traps, social media. Eco-Explore, Cardiff     
Developed materials and taught courses on UK bird identification, the use of camera traps in ecology, and social media for scientists  

2016 Lecturer and field ornithologist. Operation Wallacea, Ecuador   
Co-developed and delivered a 5-part series of lectures focussing on rainforest biodiversity and conservation, and conducted bird ringing studies including demonstrating techniques and training students in biometric data gathering. Also trained an assistant on mist nest extraction and data recording   

2015 Otter surveys, MSc, Queen's University Belfast  
Trained a Master's student in otter survey techniques and field signs, and advised on camera trap survey methodology   

## Fieldwork experience
2018	  Camera trapping, small mammal trapping, bird point counts. Upland areas.  
2017	  Hen Harrier nest surveys. Upland areas.  
    	  Breeding Bird Survey (BTO).	 Upland areas; windfarm-adjacent.  
2016	  Bird, bat and reptile surveys and camera trapping. South American rainforest.  
2015	  Camera trapping for otters. Rivers and riparian areas.  
2014	  Badger sett surveys. Broadleaved woodlands.  
2012-15	Hare surveys (distance sampling, camera traps, fecal). Uplands and agricultural.  
2013	  Coastal biodiversity surveys. Tidal pools.  
2012	  Wader and gull surveys. Tidal flats.   
2011	  Small mammal trapping. Agricultural fields.  
      	Reptile surveys. Clearfell areas in coniferous forests.  
      	Bird point count, reptile, mammal and invertebrate surveys. Marsh and fen.  
      	Bat roost surveys (visual and detector). Urban areas.  
      	Great crested newt surveys. Agricultural areas.  
      	Bird surveys. Broadleaved woodland.  
2009-11	Breeding Bird Surveys (BTO). Upland areas.  
2007-18	Bird ringing (mist, whoosh and cannon nets and traps). Woodland, fen, marsh, grassland, coastal and agricultural areas.  
2007-09	Pine marten surveys. Coniferous woodland.  
2007	  Passerine bird and invertebrate surveys. Shrub and broadleaved woodland.  
	      Moth trapping. Treborth Botanic gardens.  
2006-08	Bird surveys and nestbox monitoring. Broadleaved woodland.   


## Fellowships, funding and Awards
2018 Funded postgraduate programme (PhD), &euro;96,000, Irish Research Council    
2017 Project tender, &euro;174,000, National Parks and Wildlife Service     
2015 Emily Sarah Montgomery Travel Scholarship, &pound;200, Queen's University Belfast  
2015 Training and Travel grant, &pound;500, British Ecological Society    
2012 Research grant, &pound;2,000, People's Trust for Endangered Species    
2012 NIEA funded PhD studentship, &pound;82,720, Queen's University Belfast     
2010 NERC Master's scholarship, &pound;7,500, University of Leeds  

## Presentations
> **Conferences** (*oral presentations*)     

12 **Caravaggi A**, Montgomery WI, Reid N (2017) An invasion in progress: Impacts of the non-native European hare on the native Irish hare. International Congress for Conservation Biology, Cartagena    

11 **Caravaggi A** (2017) The changing face of UK conservation. Mammal Society Student Conference (*invited keynote*)   

10 **Caravaggi A** (2017) University Mammal Challenge: distributed mammal surveys with student scientists. Mammal Society Spring Conference, Cambridge  

9 **Caravaggi A**, Montgomery WI, Reid N (2016) Invasion ecology: quantifying the impact of non-native European hares on the endemic Irish hare. British Ecological Society Annual Meeting, Liverpool

8 **Caravaggi A**, Hayward M (2016) People and hedgehogs in Wales. North Wales Mammal Symposium, Bangor

7 **Caravaggi A**, Montgomery WI, Reid N (2016) Invasion ecology: quantifying the impact of non-native European hares on the endemic Irish hare. Mammal Society Spring Conference, Yarnfield  

6 **Caravaggi A** 2015	Quantifying endemic uniqueness and ecological equivalency between native and invasive leporids. 7th European Congress of Mammalogy, Stockholm, Sweden  

5 **Caravaggi A**, Leach K, Santilli F, Rintala J, Helle P, Tiainen J, Bisi F, Martinoli A, Montgomery WI, Reid N (2015) Democratisation of invasive species interventions: assessing attitudes towards lethal control of mammalian invaders. Mammal Society Spring Conference, Lancaster  

4 **Caravaggi A**, Zaccaroni M, Riga F, Schai-Braun SC, Dick JTA, Montgomery WI, Reid N (2015) Using the Random Encounter Model to estimate spatial patterns in invasive and native hare densities in allopatry and sympatry. Mammal Society Student Conference, Lancaster  

3 **Caravaggi A**, Montgomery WI, Reid N (2014) Using the Random Encounter Model to estimate spatial patterns in invasive and native hare densities in allopatry and sympatry. Mammal Society Spring Conference, Birmingham  

2 **Caravaggi A**, Montgomery WI, Reid N (2013) Distribution and differential habitat associations of invasive European and endemic Irish hares. 11th International Mammal Congress, Belfast  

1 **Caravaggi A**, Montgomery WI, Reid N (2013) Invasion ecology: quantifying the impact of non-native European hares on the endemic Irish hare. Mammal Society Student Conference, Staffordshire   

> **Conferences** (*posters*)   

9 **Caravaggi A**, Vallely M-C, Hogg K, Freeman M, Fadaei E, Reid N, Tosh D (2017) Activity and temporal relationships of free-ranging mammals revealed by camera traps. Mammal Society Spring Conference, Cambridge   

8 **Caravaggi A**, Montgomery WI, Reid N (2015) The democratisation of conservation: public attitudes towards lethal control of invasive leporids and implications for species management. 7th European Congress of Mammalogy, Stockholm, Sweden  

7 **Caravaggi A**, Zaccaroni M, Riga F, Schai-Braun SC, Dick JTA, Montgomery WI, Reid N (2015) Optimising camera trap Random Encounter Model survey effort: A case study using an invasive-native species replacement process. Vth International Wildlife Management Congress, Sapporo, Japan  

6 Beresford NA, Wood MD, Gaschack S, Gulyaichenko EA, **Caravaggi A** (2015) Use of wildlife camera traps to within the Chernobyl Exclusion Zone. Mammal Society Spring Conference, Lancaster  

5 **Caravaggi A**, Montgomery WI, Reid N (2013) Estimating hare numbers using camera trapping and the Random Encounter Model. 11th International Mammal Congress, Belfast  

4 **Caravaggi A**, Montgomery WI, Reid N (2012) Invasion ecology: quantifying the impact of non-native European hares on the endemic Irish hare.  2nd All Ireland Mammal Symposium (AIMS), Dublin  

3 **Caravaggi A**, Montgomery WI, Reid N (2012) Invasion ecology: quantifying the impact of non-native European hares on the endemic Irish hare.  4th World Lagomorph Conference, BOKU, Vienna  

2 **Caravaggi A**, Hughes W (2011) Patrilineal inheritance of grooming behaviour and parasite resistance in leaf-cutting ants (Acromyrmex sp.). Postgraduate Student Forum, University of Leeds    

1 **Caravaggi A**, Bishop, C (2009)  Dietary and faecal iron levels in captive black-and-white ruffed lemurs (Varecia spp.). 11th BIAZA Research Symposium, Blackpool  

> **Invited seminars**

2014	Distribution and differential habitat associations of invasive European and endemic Irish hares. Bangor University    

## Conference organisation

2018    2nd Biotweeps Twitter Conference, #BTCon18 (*principal organiser*).  
2017    7th Irish Ornithological Research Conference (*scientific committee*).    
2017    Biotweeps Twitter Conference, #BTCon17 (*conception and organisation*).    
2014-18 Mammal Society Student Conference (*principal organiser*).    

## Personal development
> **Training and workshops**

2018 Postgraduate Certificate in Teaching and Learning in Higher Education.  
     Unconscious bias awareness.  
     Developing Horizon 2020 grant applications.  
2017 Postgraduate Certificate in Teaching and Learning in Higher Education, University College Cork.  
     NERC Advanced Training, Systematic Review and Meta-Analysis, University of East Anglia.   
     Level 3 Teaching Assistant, E-Training Hub.    
     Public Outreach, Science Made Simple.  
2016 Mentor Training, British Ecological Society.  
     Conservation Ecology Special Interest Group workshop, British Ecological Society Annual Meeting.  
     Acoustic Analysis, North Wales Mammal Symposium.    
2014 Using R, Queen's University Belfast.  
2012 Lagomorph Systematics, 4th World Lagomorph Conference.  

> **Licenses and Certifications**

2018 LAST Ireland (animal welfare in research; License no: 09-2018)     
2014 ASPA laboratory animal handling license (TSA/47/14)   
2014 Emergency first aid; field first aid  
2009 Bird ringing 'C' license holder, British Trust for Ornithology   
2008 Marine mammal medic, British Divers Marine Life Rescue     
2002 Full manual UK driving license, held without incident or penalty    

> **Societal memberships**

(since)   
2017 British Ornithologist's Union  
2015 South Wales Mammal Group; Welsh Ornithological Society  
2013 Society of Conservation Biology (SCB)  
2012 The Mammal Society; British Ecological Society   
2011 Royal Society of Biology  
2009 The British Trust for Ornithology   

> **Organisational and Working Groups**  

(since)   
2017 SCB Participatory and Citizen Science  
2016 South Wales Mammal Group (*committee*)  
2016 British Ecological Society Review College   
2013 SCB Urban Ecology  

> **Additional roles**

<!---
2017 		**Volunteer**, The Mammal Society Spring Conference
2013 		**Volunteer**, 11th International Mammal Congress, Belfast    
2010-12	**Volunteer**. Royal Society for the Protection of Birds  
2010-11 **Volunteer** Conservation Volunteers, Leeds University   
2008-08 **Volunteer**, Treborth Botanic Gardens, Bangor  
--->

2018-19 UCC BEES Education and Public Engagement Committee.   
2016-18	University Mammal Challenge, The Mammal Society (coordinator).    
2016 		Community Ecology session chair, British Ecological Society Annual Meeting.  
        Advisor to National Geographic on red fox ecology.  
        British Ecological Society Women in Ecology (WIE) mentor.  
        Mammal (hares) consultant for The Mammal Society.     
2013    Wildlife consultant, Biological records for the North East of Scotland (NESBReC).  
2013-17 UK STEM Ambassador.  
2012-15	EBEE postgraduate representative, Queen's University Belfast.  
2012-15	SBS Athena SWAN committee, Queen's University Belfast.   
2007-09	Undergraduate student representative, Bangor University Biological Sciences.  
      	Founding committee & publicity officer, Bangor University Zoological Society.   

> **Science communication**  

I am a strong supporter of science communication and outreach. I believe that it is important to encourage an interest in science and the natural world in people of all ages. Moreover, the success or failure of many modern conservation objectives increasingly require a connection with and understanding of the public. I have given talks to over 20 school, local interest, community and natural history groups in the UK, USA and Canada, in-person and via video calls.  

*Contributions*  
2018	UCC BEES Committee for Education and Public Engagement.    
      BBC Wildlife magazine feature on wallabies (*invited expert*).   
      I'm a Scientist Get Me Out of Here! Careers Zone expert.   
2017	Sanger Institute 25 Genomes (*species champion - St. Kilda wren*).  
    	Culture Night, University College Cork.   
    	Blog post - A brief history of an Early Career Researcher, Errant Science.  
    	Conservation & ecology expert on the sub-reddit /r/AskScience.    
    	Blog post - Rejected by the Rainforest, I F-ing Love Conservation.     
    	Science communication article, CBS (*#bestcarcass, contributor*).   
    	Rabaiotti D, Caruso N 2017. Quercus books, ISBN: 9781786488275 (*contributor*).    
    	Student Science Partnerships, USA.   
    	Bird song workshop and ringing demonstration, Parc Slip Nature Reserve, Wales.   
2016-18	Skype a Scientist (*5 classrooms across the US*).  
2016	Blog post - Camera traps reveal a hare-raising situation, RSEC blog, ZSL.   
      Blog post - On closer inspection, it looks like a hare transplant, QUBio.   
      Magazine article - Is there intelligent life on Earth? Save our Souls magazine (*author*).  
    	Letters to a Pre-scientist (*correspondent*).  
2015	Blog post - Putting wildlife in the frame, QUBio.    
      Blog post - Communities and conservation in developing countries, QUBio.  
      Nature News (*invited comment*).    
      Bird ringing demonstration, Parc Slip Nature Reserve, Wales.   
      Blog post - Dear Alice, the hare might be sane after all, QUBio.     
      Blog post - What's in a name? QUBio.       
2014-16	Various Local Mammal Group newsletters (*invited author*).  
    	Created @Biotweeps, a science communication Twitter project (>16.5k followers).    
    	Multi-school careers advice and speed-networking event (*invited expert*).   
2013-18	I'm a Scientist Get Me Out of Here! Enquiry Zone & Careers Zone.      
2013-17	UK STEM Ambassador.   
2013	Science outreach event, Techniquest, Cardiff (*presenter for RSPB*).  

<!---
2016 **Remote project group mentor**, Beaumont Middle School, Kentucky
2016 **Project development and advisor**, class conservation project, Ysgol Rhydywaun, Wales  
2015 **Interactive presentation**, Natives and non-natives, St. Pius X. College, Magherafelt   
2015 **School presentation**, The Irish hare, Rathlin Island School   
2014 **Presentation**, Hares in Northern Ireland, An Carn  
2014 **Presentation**, Island biodiversity, with a focus on hares, Magherafelt bird group   
2014 **Presentation**, Hares in Northern Ireland, Toome local RSPB group   
2013 **Presentation**, Hares in Northern Ireland, Maghera Naturalists   
--->

> **Media engagements**

*Radio*    

2018 BBC Radio Wales, UK.   
	   BBC Radio Derby, UK.    
	   MostlyScience live (*podcast*).   
2017 BBC Coventry & Warwickshire, Wallabies in the UK.   
     The Edgar Ortega Radio Show, North America (*podcast*).    
2016 SciComm with Dr. Mike (*podcast, 2 shows*).    
2015 BBC Radio Ulster, Hares at Belfast airport.       
     BBC News School Report for St. Pius X, Magherafelt's Biodiversity Club.    
     BBC Radio Ulster, *Good Morning Ulster*,  Invasive species.     
2013 RTE Radio 1, *Mooney Goes Wild*, Hares in Ireland.     

*Television*    

2015 Countryfile, BBC  
2013 River Bann, RTE Television  

*Other media*  

2018	BBC Wildlife (invited article).    
2017	The Washington Post (*interview*).   
2016	National Geographic advisor (*mammal expert*).   
      Biotechin.asia (*interview*).  
2015	Media battle highlights importance of scientific credit. ScienceNews (*interview*).     
      Astrotweeps and Biotweeps: rotating Twitter accounts. Crastina.se (*interview*).   
      BBC News (*interview and featured article*).  
      A call for beautiful prose in papers. Nature News (*Interview*).      
2014	Species profiles: Mountain hare and Irish hare, The Mammal Society.    
2013  'Hare' raising project in Mid-Ulster, Mid Ulster Mail (*Interview*).     

## Skills  
> *Analytical sotware*   

R, SPSS, Minitab, Distance, MARK, ArcGIS, QGIS, MaxEnt, NetLogo, MAVIS NVC, Patch Analyst, GeneMapper,  bespoke software.  

> *Additional tools*  

Microsoft Office, GitHub, RMarkdown, graphics packages (e.g. Adobe creative suite), website creation.   

> *Statistical*  

General linear and mixed-effects models, Principal Components Analysis, Species Distribution Modelling, Discriminant Function Analysis, diversity indices, Mahalanobis and Euclidean distance, cross-correlation functions, model averaging, Random Encounter Models, meta-analysis, other parametric and non-parametric tests

> *Field*  

Off-road driving (4x4), multi-taxa (mammal, bird, invertebrate, reptile, amphibian; UK coastal, marine and terrestrial) surveys (e.g. mark and recapture, distance sampling, camera traps, quadrats, scan/focal sampling;) and identification, habitat surveys, animal handling (amphibians, reptiles, invertebrates, and small-to-large birds and mammals), orienteering  

<!---
2017	Assistant, pied flycatcher nestbox monitoring, Cardiff University  
2017	Breeding Bird Survey, British Trust for Ornithology    
2011-12	Small mammal surveys, field assistant, University of Leeds    
2011-12	Ecologist, great crested newt and bat surveys, Haycock and Jay, Ecologists    
2011-12 	Habitat management, Conservation Volunteers, University of Leeds    
2011 	Bat survey assistant, Haycock and Jay, Ecologists     
2011	Snake survey assistant, Dr. Axel Barlow  
2010-11 	Ornithological technician, bird territory mapping, Cardiff University    
2010-11 	Breeding Bird Surveys, British Trust for Ornithology    
2010 	Wading bird surveys, British Trust for Ornithology    
2009 	Data analyst, butterfly foodwebs, Bangor University    
2007-09 	Pine marten surveys, Snowdonia Mammal Group  
2007-09 	Woodland bird and invertebrate surveys, Treborth Botanic Gardens, Bangor  
2006-08	Ornithological technician, bird breeding and behaviour, Dr. Geoff Gibbs  
--->   

> *Laboratory*  

Multi-taxa dissection (mammal, bird, amphibian, invertebrate), species identification via microscopy, ethological studies, tissue sampling, DNA manipulation, electrophoresis, atomic absorption and colourimetric spectroscopy, specimen preparation, soil chemical and biological analysis   

\newpage

## Referees
**Prof. John O'Halloran**	  
School of BEES, University College Cork, Distillery Field, N Mall, Ireland   
**Email** j.ohalloran@ucc.ie   **Tel** +353 (0)21 490 2407  

**Dr. Sandra Irwin**   
School of BEES, University College Cork, Distillery Field, N Mall, Ireland   
**Email**: s.irwin@ucc.ie   	**Tel** +353 (0)21 490 4595   

**Dr. Neil Reid**  
School of Biological Sciences, Medical Biology Centre, 97 Lisburn Road, Belfast BT9 7BL     
**Email** neil.reid@qub.ac.uk   **Tel** +44 (0)28 9097 2746

**Prof. Ian Montgomery**  
School of Biological Sciences, Medical Biology Centre, 97 Lisburn Road, Belfast BT9 7BL     
**Email** i.montgomery@qub.ac.uk  **Tel** +44 (0)28 9097 2214	  

**Prof. Jaimie Dick**   
School of Biological Sciences, Medical Biology Centre, 97 Lisburn Road, Belfast BT9 7BL       
**Email** j.dick@qub.ac.uk  **Tel** +44 (0)28 9097 2286  

**Dr. Tom Cameron**  
School of Biological Sciences, University of Essex, Wivenhoe Park, Colchester, CO4 3SQ  
**Email** tcameron@essex.ac.uk	**Tel** +44 (0)1206 874074
